name : Skkuding study week8 CD 

on:
  push:
    branches: [main]

jobs:
  job1:
    name: AWS S3 Sync
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::652258230505:role/skkuding_identity
          aws-region: ap-northeast-2
      - name: Upload static files
        run: aws s3 sync week8 s3://skkuding
  job2:
    name: Update ECS
    runs-on : ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: arn:aws:iam::652258230505:role/skkuding_identity
         aws-region: ap-northeast-2
     - name: Log in
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: skkuding_3
       with:
         file: 3.Docker/Dockerfile
         push: true
         tags: ${{ steps.login-ecr.outputs.registry }}/skkuding_3:latest
